global:
  hostname: <the DNS entry of your instance.  For example, ec2-1-2-3-4.compute-1.amazonaws.com>

  unattended:
    configuration:
      version: 8
      systemPassword: "<Enclose in quotes.  Encode your password per the instructions at https://docs.gradle.com/develocity/tutorials/aws-standalone/#s3_build_scans>"
      buildScans:
        storage:
          incomingStorageType: objectStorage
      advanced:
        app:
          heapMemory: 5632 <this value has to increase per the instructions at https://docs.gradle.com/develocity/tutorials/aws-standalone/#s3_build_scans>

database:
  type: embedded

ingress:
  enabled: true
  ssl:
    enabled: false



objectStorage:
  type: s3
  s3:
    bucket: <this is the name of your S3 bucket - name only, not URI, ARN.  For example, my-unique-s3-bucket-name-123456789>
    region: us-east-1
    credentials:
      source: environment